spring:
  datasource:
    url: jdbc:mysql://<RDS-ENDPOINT>:3306/library?useSSL=true&requireSSL=true&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

# 보안 로깅은 최소화
logging:
  level:
    root: INFO

# 예: actuator 엔드포인트 보호
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
